spring:
  cloud:
    stream:
      kafka:
        binder:
          application-id: 1
          brokers: 127.0.0.1:9092
      bindings:
        process-in-0:
          destination: message-in
        process-out-0:
          destination: message-out
server:
  port: 1338