spring:
  cloud:
    stream:
      kafka:
        binder:
          application-id: 1
          brokers: 127.0.0.1:9092
      bindings:
        producer-out-0:
          destination: message-in
server:
  port: 1337